### ISSUE TITLE
NullPointerException when using Java Generics

### ISSUE THREAD

**Issue by NASGregorio** [specs-feup/kadabra#1]
# Description
When analysing the example code below, Kadabra should throw a NullPointerException.
The problem appears to be from Spoon's **buildModel** method.
The exception is somehow connected to the usage of generics.
With the **<T>** removed from class **Item** the exception doesn't trigger.

# How to reproduce
Run Kadabra with an empty aspect using the code below as a source.
## Java Code Example
```
//FailsToBuildModel.java
public class FailsToBuildModel {

	private int foo = 0;
	
	private Item[] mItems = { new Item<>(foo) };

	private class Item<T> {}
}
```

### Stacktrace
```
Last exception type: class java.lang.NullPointerException
java.lang.RuntimeException: 
 when initializing the weaver
  caused by NullPointerException
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:476)
	at larai.LaraI.treatExceptionInInterpreter(LaraI.java:434)
	at larai.LaraI.execPrivate(LaraI.java:266)
	at larai.LaraI.lambda$3(LaraI.java:215)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at spoon.support.compiler.jdt.ReferenceBuilder.tryRecoverTypeArguments(ReferenceBuilder.java:608)
	at spoon.support.compiler.jdt.ReferenceBuilder.insertGenericTypesInNoClasspathFromJDTInSpoon(ReferenceBuilder.java:575)
	at spoon.support.compiler.jdt.ReferenceBuilder.getTypeReference(ReferenceBuilder.java:517)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:136)
	at spoon.support.compiler.jdt.ReferenceBuilder.buildTypeReference(ReferenceBuilder.java:130)
	at spoon.support.compiler.jdt.JDTTreeBuilder.createParameterizedType(JDTTreeBuilder.java:1450)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1438)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.traverse(ParameterizedSingleTypeReference.java:405)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:713)
	at org.eclipse.jdt.internal.compiler.ast.ArrayInitializer.traverse(ArrayInitializer.java:255)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.traverse(FieldDeclaration.java:359)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1472)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:826)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:787)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:466)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:337)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:114)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:97)
	at spoon.Launcher.buildModel(Launcher.java:755)
	at weaver.kadabra.JavaWeaver.buildAndProcess(JavaWeaver.java:550)
	at weaver.kadabra.JavaWeaver.begin(JavaWeaver.java:158)
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:174)
	at larai.LaraI.interpret(LaraI.java:663)
	at larai.LaraI.execPrivate(LaraI.java:250)
	... 5 more
*Application Stopped*
```

**Comment by joaobispo** [comment]
This code seems to have a compilation error:

![image](https://user-images.githubusercontent.com/5724365/178112757-f2de5782-74a8-4b30-9305-18f543bd7264.png)

It is solved by adding a constructor in class Item:

![image](https://user-images.githubusercontent.com/5724365/178112786-c184fc7b-69a2-4da6-b48f-ddd637c88469.png)

After doing this change, the code is correctly parsed by Spoon.
