### ISSUE TITLE
NullPointerException from folder and file with same name

### ISSUE THREAD

**Issue by NASGregorio** [specs-feup/kadabra#2]
# Description
When analysing the example code below, Kadabra should throw a NullPointerException.
The problem appears to be from Spoon's **buildModel** method.
Having a file called **a.java** and a folder called **a** with another file inside triggers the exception.
Renaming **a.java** to **c.java** doesn't trigger it.

# How to reproduce
Run Kadabra with an empty aspect using the following structure as source.

## Folder structure
```
foo  
│   a.java
│   │
│   └─── a
│        │   b.java
```

## Java Code Example
```
// a.java
package foo.bar;
public class a {}

// b.java
package foo.bar.a;
public class b {}
```

## Stacktrace
```
Last exception type: class java.lang.NullPointerException
java.lang.RuntimeException: 
 when initializing the weaver
  caused by NullPointerException
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:476)
	at larai.LaraI.treatExceptionInInterpreter(LaraI.java:434)
	at larai.LaraI.execPrivate(LaraI.java:266)
	at larai.LaraI.lambda$3(LaraI.java:215)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1747)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1438)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:826)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:787)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$0(JDTBasedSpoonCompiler.java:437)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:466)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:435)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:337)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:114)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:97)
	at spoon.Launcher.buildModel(Launcher.java:755)
	at weaver.kadabra.JavaWeaver.buildAndProcess(JavaWeaver.java:550)
	at weaver.kadabra.JavaWeaver.begin(JavaWeaver.java:158)
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:174)
	at larai.LaraI.interpret(LaraI.java:663)
	at larai.LaraI.execPrivate(LaraI.java:250)
	... 5 more
*Application Stopped*
```

**Comment by joaobispo** [comment]
This seems a problem with Spoon, an issue should be opened in their [GitHub](https://github.com/INRIA/spoon/issues/).

**Comment by joaobispo** [comment]
Java does not support package and classes with the same qualified name:

![image](https://user-images.githubusercontent.com/5724365/181924544-fe554c6b-e5bf-4324-87c4-2600bb84dde3.png)

However, this issue appeared because when using decompiled code, this is a situation that sometimes did appear. In bytecode, apparently packages and classes can have the same qualified name. In bytecode that is generated directly from Java sources this should never happen. But it can appear in bytecode that is transformed after compilation, e.g., in an obfuscation process.

To "solve" this issue, we would need a decompiler that addressed this problem, probably by performing some preprocessing at the bytecode level.
